### ISSUE TITLE
Account GetInfo() has an issue if profile doesn't exist

### ISSUE THREAD

**Issue by L00ks** [Tustin/psn-csharp#2]
Profile may not exist if user hasn't logged in a console, hence profile is empty. This happens when you just create an account online using a browser.
I've already fixed it. I can contribute if you like.

**Comment by Tustin** [comment]
Thanks for bringing this up. It's been a few months since I worked on this so if you open a pull request I'll merge it.

**Comment by Tustin** [comment]
(Finally) fixed in 00eae2e045d262dcbc43b2382cc90ad1df8beaf5
