### ISSUE TITLE
Unable to reference dll in a Xamarin.Forms project

### ISSUE THREAD

**Issue by chowarth** [Tustin/psn-csharp#5]
Because of the use of `HttpUtility.UrlDecode` within [NPGrantCodeRequest](https://github.com/Tustin/psn-csharp/blob/master/PSN/Requests/NPGrantCodeRequest.cs) the dll produced by the project cannot be referenced within a Xamarin.Forms project (Android & iOS don't have access to `System.Web`). They do however have access to the `WebUtility` class which also contains a `UrlDecode` method.

I suggest the change to make `NPGrantCodeRequest` use `WebUtility.UrlDecode` instead, so that the dependency on `System.Web` is removed and the dll can be referenced in Xamarin.Forms projects.

Ideally, it would preferable to have the project as either a PCL or .NET Standard project, but I think that's a separate (and much larger) issue.

**Comment by Tustin** [comment]
Well, cross platform usage wasn't really something I was targeting with this. However I can switch to using the other method and see if that clears up the problem.

**Comment by chowarth** [comment]
It might be something worth considering. A quick check with [.Net Portability Analyzer](https://marketplace.visualstudio.com/items?itemName=ConnieYau.NETPortabilityAnalyzer) shows that targeting `.Net Standard 1.6` would allow for full portable compatibility.

See: [psn-csharp_ApiPortAnalysis.html.zip](https://github.com/Tustin/psn-csharp/files/1259600/psn-csharp_ApiPortAnalysis.html.zip)

This would mean changing the target `.Net Framework` from `4.5.1` to `4.6.1` though, unless there's a specific reason to target `4.5.1`?

**Comment by Tustin** [comment]
Not that I'm aware of. I think that was just the version I was using when I started the project. I'll go ahead and update that as well.

**Comment by chowarth** [comment]
I'm not sure of the exact process in porting a .Net Framework library project over to a .Net Standard library, other than creating a new project...

**Comment by Tustin** [comment]
You can just re-target the framework version in the project properties. I already pushed a commit earlier this morning which re-targeted it for 4.6.1.
