### ISSUE TITLE
GetFriends() fuction: offline and all friends issue.

### ISSUE THREAD

**Issue by ShuiXinYun** [Tustin/psn-csharp#6]
Hello again, I tried this csharp api today and it works nicely. But I'm confused with the GetFriends() function in PSN/API/Account.cs. I use this part to get the friends info like this:
```
System.Collections.Generic.List<User> account_friends = account.GetFriends("online", 200);
foreach (User friend in account_friends)
        {
            Console.WriteLine("Friend ID: "+friend.Profile.onlineId + " isOnline ?: "+friend.Profile.primaryOnlineStatus);
        }
```
it works fine when online friends info is checked.
In the code there's comment like this:
`/// <param name="filter">A filter to grab online, offline or all friends. Defaults to online.</param>`
so then I replace "online" with "offline" and "all", but it gives error both.
What keywords should I use to get all friends info or offline frends info?
Thanks.

**Comment by ShuiXinYun** [comment]
Oh I found solution in your psn-php issues, here--> https://github.com/Tustin/psn-php/issues/33
I just remove `&userFilter={filter}` from the url and get all friends info, that will work for me ^_^

**Comment by Tustin** [comment]
I believe there's a special flag you can use instead of "online" to get all the friends. I can't remember what it is exactly, but IIRC someone had this same question with my PHP version of this and they figured out what to use to get all friends. I'll see if I can find that again.

**Comment by Tustin** [comment]
Never mind, seems like they came to the same conclusion as you. I'll modify this function and make an enum for the status that makes it easier to get all your friends or just the online friends.

**Comment by Tustin** [comment]
cefb8a3d59c5ca19adaab7f577e0f555a430c2cb
